### ISSUE TITLE
weixinhost 确实很棒，能否加上 hprose RPC 支持？

### ISSUE THREAD

**Issue by andot** [weixinhost/libraries#1]
今天在 http://open.weixinhost.com/doc#什么是RPC服务 看到 weixinhost 上有提供 RPC 服务，感觉很不错。这里还有另外一款 RPC 接口，也非常方便，那就是 [hprose](https://github.com/andot/hprose)，hprose 是一个支持 20多种常用语言的 RPC，同样支持同步，异步等多种调用方式，开发部署也非常方便，其 php 扩展的序列化速度甚至超过 msgpack。而且还支持 javascript 跨域调用，其目前也有众多的用户，所以是否可以在 weixinhost 也加入 hprose RPC 的支持呢？

**Comment by leeeboo** [comment]
感谢你的支持~！我们也在考虑增加更多的RPC协议，会考虑你提出的方案！
